### ISSUE TITLE
Crash while swiping

### ISSUE THREAD

**Issue by msfjarvis** [saket/swipe#19]
Haven't had the chance to fully debug it yet but I got this crash reported for my app on Sentry

<details>
<summary>Stacktrace</summary>

```
kotlin.UninitializedPropertyAccessException: lateinit property canSwipeTowardsLeft has not been initialized
    at me.saket.swipe.SwipeableActionsState.getCanSwipeTowardsLeft$swipe_release
    at me.saket.swipe.SwipeableActionsState$draggableState$1.invoke
    at me.saket.swipe.SwipeableActionsState$draggableState$1.invoke
    at kotlinx.serialization.descriptors.SerialDescriptorImpl$toString$1.invoke$bridge(SourceFile:0)
    at androidx.compose.foundation.gestures.DefaultDraggableState$dragScope$1.dragBy
    at androidx.compose.foundation.gestures.DefaultDraggableState$dragScope$1.dragBy$bridge
    at androidx.compose.foundation.gestures.DraggableNode$onAttach$1$1.invokeSuspend
    at androidx.compose.foundation.gestures.DraggableNode$onAttach$1$1.invoke
    at androidx.compose.foundation.gestures.DraggableNode$onAttach$1$1.invoke
    at androidx.compose.foundation.MutatorMutex$mutateWith$2.invokeSuspend
    at androidx.compose.foundation.MutatorMutex$mutateWith$2.invoke
    at androidx.compose.foundation.MutatorMutex$mutateWith$2.invoke
    at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn
    at okio.Utf8.processUtf16Chars
    at kotlinx.coroutines.CoroutineScopeKt.coroutineScope
    at kotlinx.coroutines.CoroutineScopeKt.coroutineScope
    at androidx.compose.foundation.MutatorMutex.mutateWith
    at androidx.compose.foundation.gestures.DefaultDraggableState$drag$2.invokeSuspend
    at androidx.compose.foundation.gestures.DefaultDraggableState$drag$2.invoke
    at androidx.compose.foundation.gestures.DefaultDraggableState$drag$2.invoke
    at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn
    at okio.Utf8.processUtf16Chars
    at kotlinx.coroutines.CoroutineScopeKt.coroutineScope
    at kotlinx.coroutines.CoroutineScopeKt.coroutineScope
    at androidx.compose.foundation.gestures.DefaultDraggableState.drag
    at androidx.compose.foundation.gestures.DraggableNode$onAttach$1.invokeSuspend
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith
    at kotlinx.coroutines.DispatchedTask.run
    at kotlinx.coroutines.DispatchedTask.run
    at androidx.compose.ui.platform.AndroidUiDispatcher.nextTask
    at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch
    at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch
    at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch
    at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch
    at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7356)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

</details>

Here's how I'm using Swipe: https://github.com/msfjarvis/compose-lobsters/commit/bae671ad231beb776d0267541eaa278dd1f18ea4

**Comment by saket** [comment]
I wasn't expecting touch events to be received before those lateinit properties are set. Thanks for reporting! You can use `1.3.0-SNAPSHOT` if you want to try out the fix.

**Comment by msfjarvis** [comment]
Thanks! The crash is fixed but I'm seeing a different problem now. I use the swipe action to open a custom tab and if the swipe reset duration is longer than the time it takes to launch the browser, the list item appears to remain stuck until you swipe on it again.

You can reproduce it using the APK from here: https://github.com/msfjarvis/compose-lobsters/releases/tag/nightly

Try swiping on any story all the way from right to left, then releasing. When you close the custom tab and go back to the app the item should be stuck.

**Comment by arkon** [comment]
Should we expect a `1.3.0` release anytime soon?
