### ISSUE TITLE
Crash when swiped to full width

### ISSUE THREAD

**Issue by alashow** [saket/swipe#7]
Crash happens when swiping/dragging content to it's full width.

Stacktrace:
```ruby
java.lang.IllegalStateException: Couldn't find any swipe action. Width=1160, offset=1162.4507, actions=[me.saket.swipe.SwipeAction@c737efb, me.saket.swipe.SwipeAction@effbb18]
 	at me.saket.swipe.ActionFinder.actionAt(ActionFinder.kt:49)
 	at me.saket.swipe.ActionFinder.actionAt(ActionFinder.kt:24)
 	at me.saket.swipe.SwipeableActionsBoxKt$SwipeableActionsBox$1.invoke(SwipeableActionsBox.kt:82)
 	at me.saket.swipe.SwipeableActionsBoxKt$SwipeableActionsBox$1.invoke(SwipeableActionsBox.kt:56)
 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
```

Screenrecord: https://kapture-4t6s5u7zc-alashov.vercel.app

**Comment by alashow** [comment]
This can be fixed by returning the last action like this:
https://github.com/saket/swipe/blob/63483bd3886e65b0d6228b9c66e3e49108e93594/swipe/src/main/kotlin/me/saket/swipe/ActionFinder.kt#L49

<img width="954" alt="image" src="https://user-images.githubusercontent.com/5840013/166165138-0df29d79-4091-4457-9b95-0b2231d79a3d.png">

How it looks: https://i.imgur.com/XLYdlNg.gif

**Comment by saket** [comment]
Fixed, thanks for reporting!
